# Generated by Django 6.0.2 on 2026-02-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookconsultation',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
