# Generated by Django 6.0.2 on 2026-02-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_consultation', '0002_alter_bookconsultation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookconsultation',
            name='branch',
            field=models.CharField(default='west', max_length=50),
            preserve_default=False,
        ),
    ]
