# Generated by Django 5.2.11 on 2026-02-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'our_services',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='our_service_is_acti_69a927_idx'), models.Index(fields=['created_at'], name='our_service_created_f77f2b_idx')],
            },
        ),
    ]
