# Generated by Django 5.2.11 on 2026-02-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ourservices',
            name='our_service_is_acti_69a927_idx',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='is_active',
        ),
    ]
