# Generated by Django 5.2.11 on 2026-02-11 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_services', '0002_remove_ourservices_our_service_is_acti_69a927_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutismCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autism_then', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('autism_now', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Autism',
            },
        ),
    ]
