# Generated by Django 5.2.11 on 2026-02-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_services', '0003_autismcount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autismcount',
            table='autism',
        ),
    ]
