# Generated by Django 6.0.2 on 2026-02-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_services', '0004_alter_autismcount_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='icon',
            field=models.CharField(default='Star', max_length=30),
            preserve_default=False,
        ),
    ]
