# Generated by Django 5.2.11 on 2026-02-11 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_exprience', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('happy_students', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('branches', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('qualified_teachers', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'home_stats',
            },
        ),
    ]
