# Generated by Django 5.2.11 on 2026-02-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homestats',
            old_name='year_of_exprience',
            new_name='years_of_experience',
        ),
    ]
