# Generated by Django 5.2.11 on 2026-02-11 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_year_of_exprience_homestats_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestats',
            name='students_enrolled',
            field=models.PositiveIntegerField(default=780, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
