# Generated by Django 6.0.2 on 2026-02-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(unique=True)),
                ('video_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.URLField(blank=True)),
                ('view_count', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'youtube',
                'ordering': ['-updated_at'],
            },
        ),
    ]
