# Generated by Django 6.0.2 on 2026-02-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='tiny@gmail.com', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
