# Generated by Django 6.0.2 on 2026-02-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
