# Generated by Django 6.0.2 on 2026-02-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_contact', '0002_customercontact_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_count', models.IntegerField(default=0)),
            ],
        ),
    ]
