# Generated by Django 6.0.2 on 2026-02-13 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('parent_statisfaction', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('improvement_rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('early_detection', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('phone_no_one', models.CharField(max_length=20)),
                ('phone_no_two', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'about',
            },
        ),
    ]
