# Generated by Django 6.0.2 on 2026-02-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='parent_statisfaction',
            new_name='parent_satisfaction',
        ),
    ]
